### ISSUE TITLE
Preferences window doesn't stay around

### ISSUE THREAD

**Issue by ketzusaka** [modcloth-labs/XBotBuilder#3]
The preferences window doesn't stay around after opening it. It'd be nice if it did when going to copy/paste other things into it.

I think it should stay around. If this is something you're open to, you can assign the issue to me and I'll add it in.

**Comment by nixterrimus** [comment]
Thanks!

We have another report of this being annoying.  I'll fix this pretty soon.

**Comment by nixterrimus** [comment]
Done!
